import blueBrick from "./cards-2/blue-player/blue-brick.png"
import blueGold from "./cards-2/blue-player/blue-gold.png"
import blueGrain from "./cards-2/blue-player/blue-grain.png"
import blueLumber from "./cards-2/blue-player/blue-lumber.png"
import blueOre from "./cards-2/blue-player/blue-ore.png"
import blueWool from "./cards-2/blue-player/blue-wool.png"

import redBrick from "./cards-2/red-player/red-brick.png"
import redGold from "./cards-2/red-player/red-gold.png"
import redGrain from "./cards-2/red-player/red-grain.png"
import redLumber from "./cards-2/red-player/red-lumber.png"
import redOre from "./cards-2/red-player/red-ore.png"
import redWool from "./cards-2/red-player/red-wool.png"

import road from "./cards-2/blue-player/road-back.png"
import settlement from "./cards-2/blue-player/settlement-back.png"

export interface CardDefinition {
  type: string // might remove, change to card name
  display: string // might remove
  resourceType: string
  resourceCount: number
  diceNumber: number | undefined
  index: number
  image: string | undefined
  buildingType: string | undefined
  rotation: number
  minRotation: number
  maxRotation: number
  commercePoints: number | undefined
  strengthPoints: number | undefined
  progressPoints: number | undefined
  skillPoints: number | undefined
  victoryPoints: number | undefined
  resourceMultiplyer: string
}

export const blueStartingCards: CardDefinition[] = [
  {
    type: "none",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 0,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "build",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 1,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "none",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 2,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "build",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 3,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "none",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 4,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "build",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 5,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "none",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 6,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "build",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 7,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "none",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 8,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "build",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 9,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "none",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 10,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "region",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 11,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "build",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 12,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "region",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 13,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "build",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 14,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "region",
    display: "yes",
    resourceType: "lumber",
    resourceCount: 1,
    diceNumber: 3,
    index: 15,
    image: blueLumber,
    buildingType: "region",
    rotation: 0,
    minRotation: 90,
    maxRotation: -180,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "build",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 16,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "region",
    display: "yes",
    resourceType: "gold",
    resourceCount: 0,
    diceNumber: 4,
    index: 17,
    image: blueGold,
    buildingType: "region",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "build",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 18,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "region",
    display: "yes",
    resourceType: "grain",
    resourceCount: 1,
    diceNumber: 5,
    index: 19,
    image: blueGrain,
    buildingType: "region",
    rotation: 0,
    minRotation: 90,
    maxRotation: -180,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "build",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 20,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "region",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 21,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "none",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 22,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "settlement",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 23,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "road",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 24,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "settlement",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 25,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "road",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 26,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "settlement",
    display: "yes",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 27,
    image: settlement,
    buildingType: "settlement",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 1,
    resourceMultiplyer: "",
  },
  {
    type: "road",
    display: "yes",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 28,
    image: road,
    buildingType: "road",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "settlement",
    display: "yes",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 29,
    image: settlement,
    buildingType: "settlement",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 1,
    resourceMultiplyer: "",
  },
  {
    type: "road",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 30,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "settlement",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 31,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "none",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 32,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "region",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 33,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "build",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 34,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "region",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 35,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "build",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 36,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "region",
    display: "yes",
    resourceType: "brick",
    resourceCount: 1,
    diceNumber: 2,
    index: 37,
    image: blueBrick,
    buildingType: "region",
    rotation: 0,
    minRotation: 90,
    maxRotation: -180,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "build",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 38,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "region",
    display: "yes",
    resourceType: "wool",
    resourceCount: 1,
    diceNumber: 1,
    index: 39,
    image: blueWool,
    buildingType: "region",
    rotation: 0,
    minRotation: 90,
    maxRotation: -180,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "build",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 40,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "region",
    display: "yes",
    resourceType: "ore",
    resourceCount: 1,
    diceNumber: 6,
    index: 41,
    image: blueOre,
    buildingType: "region",
    rotation: 0,
    minRotation: 90,
    maxRotation: -180,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "build",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 42,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "region",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 43,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "none",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 44,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "build",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 45,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "none",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 46,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "build",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 47,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "none",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 48,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "build",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 49,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "none",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 50,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "build",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 51,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "none",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 52,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "build",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 53,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "none",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 54,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
]

export const redStartingCards: CardDefinition[] = [
  {
    type: "none",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 0,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "build",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 1,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "none",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 2,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "build",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 3,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "none",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 4,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "build",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 5,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "none",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 6,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "build",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 7,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "none",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 8,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "build",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 9,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "none",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 10,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "region",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 11,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "build",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 12,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "region",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 13,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "build",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 14,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "region",
    display: "yes",
    resourceType: "lumber",
    resourceCount: 1,
    diceNumber: 2,
    index: 15,
    image: redLumber,
    buildingType: "region",
    rotation: 0,
    minRotation: 90,
    maxRotation: -180,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "build",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 16,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "region",
    display: "yes",
    resourceType: "gold",
    resourceCount: 0,
    diceNumber: 1,
    index: 17,
    image: redGold,
    buildingType: "region",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "build",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 18,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "region",
    display: "yes",
    resourceType: "grain",
    resourceCount: 1,
    diceNumber: 6,
    index: 19,
    image: redGrain,
    buildingType: "region",
    rotation: 0,
    minRotation: 90,
    maxRotation: -180,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "build",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 20,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "region",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 21,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "none",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 22,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "settlement",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 23,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "road",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 24,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "settlement",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 25,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "road",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 26,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "settlement",
    display: "yes",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 27,
    image: settlement,
    buildingType: "settlement",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 1,
    resourceMultiplyer: "",
  },
  {
    type: "road",
    display: "yes",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 28,
    image: road,
    buildingType: "road",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "settlement",
    display: "yes",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 29,
    image: settlement,
    buildingType: "settlement",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 1,
    resourceMultiplyer: "",
  },
  {
    type: "road",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 30,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "settlement",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 31,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "none",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 32,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "region",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 33,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "build",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 34,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "region",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 35,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "build",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 36,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "region",
    display: "yes",
    resourceType: "brick",
    resourceCount: 1,
    diceNumber: 3,
    index: 37,
    image: redBrick,
    buildingType: "region",
    rotation: 0,
    minRotation: 90,
    maxRotation: -180,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "build",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 38,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "region",
    display: "yes",
    resourceType: "wool",
    resourceCount: 1,
    diceNumber: 4,
    index: 39,
    image: redWool,
    buildingType: "region",
    rotation: 0,
    minRotation: 90,
    maxRotation: -180,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "build",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 40,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "region",
    display: "yes",
    resourceType: "ore",
    resourceCount: 1,
    diceNumber: 5,
    index: 41,
    image: redOre,
    buildingType: "region",
    rotation: 0,
    minRotation: 90,
    maxRotation: -180,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "build",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 42,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "region",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 43,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "none",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 44,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "build",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 45,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "none",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 46,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "build",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 47,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "none",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 48,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "build",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 49,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "none",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 50,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "build",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 51,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "none",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 52,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "build",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 53,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
  {
    type: "none",
    display: "no",
    resourceType: "",
    resourceCount: 0,
    diceNumber: 0,
    index: 54,
    image: "",
    buildingType: "",
    rotation: 0,
    minRotation: 0,
    maxRotation: -270,
    commercePoints: 0,
    strengthPoints: 0,
    progressPoints: 0,
    skillPoints: 0,
    victoryPoints: 0,
    resourceMultiplyer: "",
  },
]
